# Generated by Django 5.0.1 on 2024-05-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, db_collation='utf8_persian_ci', unique=True),
        ),
    ]
