# Generated by Django 5.0.1 on 2024-05-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ManyToManyField(blank=True, related_name='images', to='store.picture'),
        ),
    ]
