# Generated by Django 5.0.1 on 2024-05-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_size_remove_product_size_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='sizes',
        ),
    ]
