# Generated by Django 5.0.6 on 2024-05-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
