# Generated by Django 5.0.6 on 2024-05-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_category_description_category_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
