# Generated by Django 5.0.6 on 2024-05-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
