# Generated by Django 5.0.6 on 2024-05-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='insole',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_soles',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_upper',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
