# Generated by Django 5.0.6 on 2024-06-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_product_insole_product_shoe_soles_product_shoe_upper'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='farsi_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
