# Generated by Django 5.0.6 on 2024-06-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_color_farsi_name_alter_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='farsi_name',
        ),
    ]
