# Generated by Django 5.0.6 on 2024-06-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_color_farsi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='new_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
