# Generated by Django 5.0.6 on 2024-06-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_orderitem_discount_orderitem_new_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='discount_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='new_total_price',
            field=models.IntegerField(default=0),
        ),
    ]
