# Generated by Django 5.0.6 on 2024-06-02 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_rename_total_price_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_amount',
            new_name='total_discount',
        ),
    ]
