# Generated by Django 5.0.6 on 2024-06-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_rename_discount_amount_order_total_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounts',
            new_name='discount',
        ),
    ]
