# Generated by Django 5.0.6 on 2024-06-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_rename_discounts_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
