# Generated by Django 5.0.6 on 2024-06-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_customer_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
