# Generated by Django 5.0.6 on 2024-06-05 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_product_new_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birth_date',
        ),
    ]
